import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";

export default function Home() {
  const [link, setLink] = useState("");

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Deeplinker
          </h1>

          <input onChange={(e) => {
            setLink(e.target.value);
          }} value={link} style={{marginTop: '20px', marginBottom: '20px'}} />

          <a href={link}>{link}</a>
        </main>
      </div>
  )
}
